# Generated by Django 5.2.8 on 2025-11-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('transport', 'Transport'), ('rent', 'Rent'), ('salary', 'Salary'), ('entertainment', 'Entertainment'), ('bills', 'Bills'), ('shopping', 'Shopping'), ('other', 'Other')], max_length=100),
        ),
    ]
