# Generated by Django 5.2.8 on 2026-01-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_userprofile_email_verification_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cooldown_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='resend_count',
            field=models.IntegerField(default=0),
        ),
    ]
