# Generated by Django 5.2.8 on 2026-01-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_userprofile_cooldown_until_userprofile_resend_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='code_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
