# Generated by Django 5.2.8 on 2025-11-28 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_transaction_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=60)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('month', models.DateField(default=11)),
                ('year', models.IntegerField(default=2025)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Budget Goal',
                'verbose_name_plural': 'Budget Goals',
                'unique_together': {('user', 'category', 'month', 'year')},
            },
        ),
    ]
