# Generated by Django 5.2.8 on 2025-11-28 21:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_budgetgoal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetgoal',
            name='month',
            field=models.IntegerField(default=11),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
