# Generated by Django 5.2.8 on 2026-01-27 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_userprofile_last_latitude_userprofile_last_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='title',
        ),
    ]
