# Generated by Django 5.2.8 on 2025-11-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_budgetgoal_month_alter_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetgoal',
            name='month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='budgetgoal',
            name='year',
            field=models.IntegerField(),
        ),
    ]
