# Generated by Django 5.2.8 on 2026-02-02 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_remove_transaction_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_latitude',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_longitude',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='location_updated_at',
        ),
        migrations.AlterField(
            model_name='budgetgoal',
            name='category',
            field=models.CharField(choices=[('income', 'Income'), ('food', 'Food & Dining'), ('transport', 'Transport'), ('housing', 'Housing'), ('bills', 'Bills & Utilities'), ('shopping', 'Shopping'), ('health', 'Health & Wellness'), ('education', 'Education'), ('other', 'Other')], max_length=60),
        ),
        migrations.AlterField(
            model_name='budgetgoal',
            name='month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='budgetgoal',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('income', 'Income'), ('food', 'Food & Dining'), ('transport', 'Transport'), ('housing', 'Housing'), ('bills', 'Bills & Utilities'), ('shopping', 'Shopping'), ('health', 'Health & Wellness'), ('education', 'Education'), ('other', 'Other')], max_length=100),
        ),
    ]
