# Generated by Django 5.2.8 on 2026-02-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_remove_userprofile_last_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetgoal',
            name='category',
            field=models.CharField(choices=[('income', 'Income'), ('food', 'Food & Dining'), ('transport', 'Transport'), ('housing', 'Housing'), ('bills', 'Bills & Utilities'), ('entertainment', 'Entertainment'), ('shopping', 'Shopping'), ('health', 'Health & Wellness'), ('education', 'Education'), ('other', 'Other')], max_length=60),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('income', 'Income'), ('food', 'Food & Dining'), ('transport', 'Transport'), ('housing', 'Housing'), ('bills', 'Bills & Utilities'), ('entertainment', 'Entertainment'), ('shopping', 'Shopping'), ('health', 'Health & Wellness'), ('education', 'Education'), ('other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email_verification_code',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
