# Generated by Django 5.2.8 on 2026-02-28 13:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_budgetgoal_tracker_bud_user_id_b19308_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='tracker_tra_user_id_b536e2_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='txn_user_type_idx',
            old_name='tracker_tra_user_id_177eba_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='txn_user_cat_idx',
            old_name='tracker_tra_user_id_d498fc_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='txn_user_type_date_idx',
            old_name='tracker_tra_user_id_a850a4_idx',
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'date'], name='txn_user_date_idx'),
        ),
    ]
