# Generated by Django 5.2.8 on 2025-12-21 20:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetgoal',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
