# Generated by Django 5.2.8 on 2025-12-22 10:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_budgetgoal_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetgoal',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
