# Generated by Django 5.2.8 on 2025-12-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_alter_budgetgoal_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetgoal',
            name='month',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='budgetgoal',
            name='year',
            field=models.IntegerField(editable=False),
        ),
    ]
