# Generated by Django 5.2.8 on 2025-12-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_alter_budgetgoal_month_alter_budgetgoal_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetgoal',
            options={},
        ),
        migrations.AlterField(
            model_name='budgetgoal',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('transport', 'Transport'), ('rent', 'Rent'), ('salary', 'Salary'), ('entertainment', 'Entertainment'), ('bills', 'Bills'), ('shopping', 'Shopping'), ('other', 'Other')], max_length=60),
        ),
    ]
