# Generated by Django 5.2.8 on 2026-01-02 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_alter_budgetgoal_options_alter_budgetgoal_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetgoal',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('food', 'Food'), ('transport', 'Transport'), ('rent', 'Rent'), ('salary', 'Salary'), ('entertainment', 'Entertainment'), ('bills', 'Bills'), ('shopping', 'Shopping'), ('other', 'Other')], max_length=60),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('food', 'Food'), ('transport', 'Transport'), ('rent', 'Rent'), ('salary', 'Salary'), ('entertainment', 'Entertainment'), ('bills', 'Bills'), ('shopping', 'Shopping'), ('other', 'Other')], max_length=100),
        ),
        migrations.CreateModel(
            name='BudgetLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'month', 'year')},
            },
        ),
    ]
